### ISSUE TITLE
Possible Forged Repository- Grandpa Spoon

### ISSUE THREAD

**Issue by shaurya0406** [ISTE-VIT/Arduino_Amplified#13]
Regarding the Project: Grandpa Spoon

The code used in the project: 
[This Repo](https://github.com/ISTE-VIT/Arduino_Amplified/blob/main/Grandpa%20Spoon/Grandpa-Spoon.ino
)
This code is coincidently the exact copy of the code provided in this blog at the end:
[The Original Repo mentioned in this blog](https://diptanshude.medium.com/?p=ecd6ec0d7266)

Its clearly visible that @nishant-giri did not even go through the code.
Let me walk you through all the instances which led me to this conclusion.

1. The first code line.
`#include<SPI.h>`
This is used to include the library which handles SPI communication.
But there is no command in the entire code which is using SPI communication protocol.

2. All the variable and function names are the same. Ohh lol, the entire idea is the same :) 

3. The biggest mistake.
`int ServoRoll = map(Roll, -75, 75, 0, 180);`
The logic behind this command is to map the values coming from the sensor which is of the range `(-90 to 90)`  after processing through the function named `FunctionsPitchRoll` and map it to (0 to 180) so that the servo rotates the head of the spoon in the opposite direction relative to the patient's hands.
Again all of this is completely dependent on the relative orientation of the sensor and the servo.
@nishant-giri simply copied the range of (-75 to 75).

Let me tell you the actual reason behind the chosen value of 75.
The reason was that the servo was stopped rotating after 75 degrees because the spoon was not attached according to the centre of the servo. Instead it was placed in such a way that it is in alignment with the rest of the spoon body and hence there was some error.
To account for this error, The 75 value was chosen.

I am aware that the original code is available in public domain, but to maintain some dignity the original repo could have been directly included instead of making another repo.

I am in full-support of open-source contributions and I was really happy to see this initiative by ISTE-VIT and wanted to participate in this.

From now on, I request ISTE-VIT to check for plagiarism as it may lead to such misunderstandings though not intentional.

**Comment by nishant-giri** [comment]
@shaurya0406, thanks for updating me about this issue. I was unaware about this as I did this project with a friend of mine 4 months ago for a hackathon and he brought this concept to me and did the major coding. I made the presentation and assisted him with the code and the circuit.

I initially thought that it was his idea and we wrote this code with his major contribution as at that time, I was unaware about your blog or project.

I respect the spirit of open source contributions and will make sure to do a research myself about possible plagiarism before trusting someone's contribution in the project.

Thank you for your input and wish you good luck.

**Comment by nishant-giri** [comment]
@jaguar017, as stated before, I respect the spirit of open source contributions and will make sure that this won't be repeated due to my negligence. Though I'm new to GitHub and Open Source but I do respect people contributions in open source.

If possible, kindly remove the invalid tag as it's my first Hacktoberfest and I accept my fault and apologize for the same.

I've also made the changes in my own repository by deleting the folder for Grandpa Spoon.
